### ISSUE TITLE
is it possible 'led' control convert to 'Sevor motor' control?

### ISSUE THREAD

**Issue by leejaeuk** [generic-beat-detector/GBD#1]
Hello, admin!

thank for your app.

I have some question about my IoT project using GBD application.
If i can modify GBD source code, is it possible 'led' control convert to 'Sevor motor' control?(maybe it possible)

I see 'GBD/maker-templates/gbd-gl.c' code it display beat through openGL right?
 (== https://www.youtube.com/watch?v=1wmrO51TZqA&feature=youtu.be )

how can i control a GPIO pin?
I mean led control source code is open to other developer?

**Comment by generic-beat-detector** [comment]
Hello leejaeuk,

Theoretically, you could use the GBD beat information in Linux POSIX shared memory
to synchronize anything in the known universe to the beats of a music stream. Simply
replace the printf() statements in "maker-templates/gbd-text-display.c" with I/O instructions
for GPIO (... you do know how to access GPIO pins, right?).

In reality, whichever physical system you are controlling should have a good response.
LED is the most natural choice for this kind of beat detection -- but yes, there is no reason
why you couldn't use anything else.

Regards,
GBD

**Comment by leejaeuk** [comment]
Oh... thank you so much to your fast response.

it is not hard to control GPIO pin. 
Currently, we want to make 'music beat synchronize dancing robot'. So we should control servo motor!

thank you again to your direction. 
I have never seen this before your response speed :)

I'm also interest about Commercial software($5 per one device). How can i support your GBD application?

**Comment by generic-beat-detector** [comment]
Yes, the commercial version for GBD was scheduled for release last month (Oct '18).
But due to certain logistics beyond our control, release has been postponed to 
next month (Dec '18). 

We appreciate your interest. You might also wish to 'watch' the repo; a new beat 
detection feature is in pre-production phase and should be incorporated by the 
end of this month (Nov '18).

Regards,
GBD
