### ISSUE TITLE
Java Maker Template

### ISSUE THREAD

**Issue by don41382** [generic-beat-detector/GBD#4]
Dear GBD-Team,

Thanks for the interesting project! I would like to use the beat detection to control my lights via my Java application. Could you assist me, building a "maker-template" for Java? That would be awesome. As I understand the communication between `gbdserver` and the maker-template is done via in-memory communication. Is this also possible via TCP/UDP?

And it would be nice if you could show a way to use the line input for live beat detection. Which kind of sound device do you suggest for the raspberrypu?

Cheers and a happy new year!
Felix

**Comment by generic-beat-detector** [comment]
Hello don41382,

Yes, communication between the `gbdserver` process (which loads the `gbd.so` DSP library) and the 
maker-template is via Linux POSIX shared memory (SHM).

As far as Java programming is concerned, I haven't the slightest clue -- yet. But I suspect what could
also work for you is a TCP/UDP server implemented in Java that receives GBD beat count info via sockets. In this scenario, `/maker-templates/gbd-text-display.c` can be ported to a TCP/UPD client, i.e. replace the  `printf(3)` statements with `write(2)`/`send(2)` system calls to a socket (how is your Linux C/C++ programming skill set in this domain?). 

There are a number of good quality RPi sound hats. For example, check [*elinux, PiHats*](https://elinux.org/index.php?title=RPi_Expansion_Boards#Sound) out. [*HifiBerry*](https://www.hifiberry.com/) has positive reviews on [*Amazon*](https://www.amazon.com/HiFiBerry-DACPLUS-RCA-DAC-RCA-Version/dp/B0147RA2PY)

Now, capture via line-in is very possible but tricky. I assume you already have read the 
[*GBD, Capture-vs-Playback*](https://github.com/generic-beat-detector/GBD/wiki/The-GBD-IoT-Framework#gbd-setups-capture-vs-playback) notes. If you still really must perform line-in ADC, let us know...

Regards,
GBD.

**Comment by don41382** [comment]
Thanks for your reply and happy new year. Sorry, my C/C++ skills are pretty basic.

I realized that Spotify also provides beat information for every song. They are quite accurate and that's why used these information for my current light setup.

Take a look at https://spotify-audio-analysis.glitch.me/

Thanks again for your help.

Cheers
Felix
