### ISSUE TITLE
Installation on RPI Zero W

### ISSUE THREAD

**Issue by SecurityJon** [generic-beat-detector/GBD#5]
Howdy, I came across this project looking for beat detection software to drive external devices, from what I can see I should be able to do this by reading the shared memory and driving things from that? 

What I can't seem to do is get the project working at all on a RPI Zero W, running the latest raspbian-lite (Linux raspberrypi 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l GNU/Linux).

Firstly, the wiki says I should run Makefile-arm-rpi to get the client working. That fails with the error 'gbdclient.c:16:28: fatal error: alsa/asoundlib.h: No such file or directory'. This was resolved by installing the 'libasound2' package which allows compilation. After this I tried to run 'sudo make Makefile install' but this failed with '/usr/lib/arm-linux-gnueabihf/alsa-lib/' and I couldn't find the package to fix it.

Next, I tried using the server which refused to start.

`
pi@raspberrypi:~/GBD` $ ./gbdserver -p 7777
Illegal instruction
`

Help?

**Comment by SecurityJon** [comment]
Reading through the documentation again, it looks like you've compiled the binary for Arm7 where as the Pi Zero is Arm6 only. If I'm correct this will force project makers to buy more expensive devices which will put them off using the project for this.

Is it possible to compile a version for ArmV6?

**Comment by generic-beat-detector** [comment]
Hello,

Freeware is for ARMv7 only. In any case,  send me an email.

GBD
